version: "3.6"

services:
  server:
    command: yarn prod
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      # Node specifics
      PORT: "3000"
      HOST: "0.0.0.0"
      NODE_ENV: "production"
      NODE_NO_WARNINGS: "1"
      # App specifics
      API_URL_BROWSER: 'http://localhost:3000'
